apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: jonaskay-com-tls
spec:
  secretName: jonaskay-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jonaskay.com
  dnsNames:
    - jonaskay.com
    - www.jonaskay.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - jonaskay.com
          - www.jonaskay.com
